services:
  app:
    build: .
    container_name: mgwsmartgov_app
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "1004:80"
    networks:
      - net_mgwsmartgov
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_ENV=local
      - DB_HOST=db
      - REDIS_HOST=redis
      - REDIS_CLIENT=phpredis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  db:
    image: mariadb:10.11
    container_name: mgwsmartgov_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - net_mgwsmartgov
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mgwsmartgov_phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "1024:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - net_mgwsmartgov

  node:
    image: node:latest
    container_name: mgwsmartgov_node
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - net_mgwsmartgov
    healthcheck:
      test: ["CMD", "node", "-v"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: tail -f /dev/null

volumes:
  mysql_data:
  node_modules:

networks:
  net_mgwsmartgov:
    driver: bridge
